<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ext_bookdatabase"
 *
 * Auto generated by Extension Builder 2017-08-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Bookdatabase',
    'description' => 'Simple Bookdatabase',
    'category' => 'plugin',
    'author' => 'Christoph Werner',
    'author_email' => 'info@itfoo.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '0.0.2',
    'clearCacheOnLoad' => 0,
    'version' => '',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
