<?php
/***************************************************************
 * Extension Manager/Repository config file for ext: "extbookdatabase"
 *
 * Auto generated by Extension Builder 2017-08-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/
$EM_CONF[$_EXTKEY] = [
    'title' => 'Bookdatabase',
    'description' => 'Simple Bookdatabase',
    'category' => 'plugin',
    'author' => 'Christoph Werner',
    'author_email' => 'info@itfoo.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];